# http://docs.travis-ci.com/user/languages/go/
language: go

go: 1.12

services:
  - docker

os:
  - linux

env:
- MYSQL_USER=root

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install: true

script:
  - script/cibuild
  - docker build -t orchestrator-travis-build .

notifications:
  email: false
