FROM mysql:5.7
LABEL maintainer="github@github.com"

RUN apt-get update
RUN apt-get install -y lsb-release
RUN apt-get install -y rsync
RUN apt-get install -y curl
RUN apt-get install -y git
RUN apt-get install -y g++
RUN rm -rf /var/lib/apt/lists/*
RUN curl -L -O https://dl.google.com/go/1.12.6
RUN tar -C /usr/local -xzf go1.12.6.linux-amd64.tar.gz
RUN ln -s /usr/local/go/bin/go /usr/bin/go

WORKDIR /go/src/github.com/github/orchestrator

COPY . .

CMD ["script/test"]
