FROM mysql:5.7
LABEL maintainer="github@github.com"

RUN apt-get update
RUN apt-get install -y lsb-release
RUN apt-get install -y rsync
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /go/src/github.com/github/orchestrator

COPY . .

CMD ["script/test"]
