DROP TABLE IF EXISTS database_instance;
CREATE TABLE database_instance (
  hostname varchar(128) NOT NULL,
  port smallint(5) unsigned NOT NULL,
  last_checked timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_attempted_check timestamp NOT NULL DEFAULT '1970-12-31 23:00:00',
  last_seen timestamp NULL DEFAULT NULL,
  uptime int(10) unsigned NOT NULL,
  server_id int(10) unsigned NOT NULL,
  server_uuid varchar(64) NOT NULL,
  version varchar(128) NOT NULL,
  binlog_server tinyint(3) unsigned NOT NULL,
  read_only tinyint(3) unsigned NOT NULL,
  binlog_format varchar(16) NOT NULL,
  log_bin tinyint(3) unsigned NOT NULL,
  log_slave_updates tinyint(3) unsigned NOT NULL,
  binary_log_file varchar(128) NOT NULL,
  binary_log_pos bigint(20) unsigned NOT NULL,
  master_host varchar(128) NOT NULL,
  master_port smallint(5) unsigned NOT NULL,
  slave_sql_running tinyint(3) unsigned NOT NULL,
  slave_io_running tinyint(3) unsigned NOT NULL,
  has_replication_filters tinyint(3) unsigned NOT NULL,
  oracle_gtid tinyint(3) unsigned NOT NULL,
  executed_gtid_set text NOT NULL,
  gtid_purged text NOT NULL,
  supports_oracle_gtid tinyint(3) unsigned NOT NULL,
  mariadb_gtid tinyint(3) unsigned NOT NULL,
  pseudo_gtid tinyint(3) unsigned NOT NULL,
  master_log_file varchar(128) NOT NULL,
  read_master_log_pos bigint(20) unsigned NOT NULL,
  relay_master_log_file varchar(128) NOT NULL,
  exec_master_log_pos bigint(20) unsigned NOT NULL,
  relay_log_file varchar(128) NOT NULL,
  relay_log_pos bigint(20) unsigned NOT NULL,
  last_sql_error text NOT NULL,
  last_io_error text NOT NULL,
  seconds_behind_master bigint(20) unsigned DEFAULT NULL,
  slave_lag_seconds bigint(20) unsigned DEFAULT NULL,
  sql_delay int(10) unsigned NOT NULL,
  allow_tls tinyint(3) unsigned NOT NULL,
  num_slave_hosts int(10) unsigned NOT NULL,
  slave_hosts text NOT NULL,
  cluster_name varchar(128) NOT NULL,
  suggested_cluster_alias varchar(128) NOT NULL,
  data_center varchar(32) NOT NULL,
  physical_environment varchar(32) NOT NULL,
  instance_alias varchar(128) NOT NULL,
  semi_sync_enforced tinyint(3) unsigned NOT NULL,
  replication_depth tinyint(3) unsigned NOT NULL,
  is_co_master tinyint(3) unsigned NOT NULL,
  replication_credentials_available tinyint(3) unsigned NOT NULL,
  has_replication_credentials tinyint(3) unsigned NOT NULL,
  PRIMARY KEY (hostname,port),
  KEY cluster_name_idx (cluster_name),
  KEY last_checked_idx (last_checked),
  KEY last_seen_idx (last_seen),
  KEY master_host_port_idx (master_host,master_port)
) ENGINE=InnoDB DEFAULT CHARSET=ascii;
