FROM golang:1.14.4
LABEL maintainer="openark@github.com"

RUN apt-get update
RUN apt-get install -y lsb-release rsync libaio1 numactl sqlite3
RUN rm -rf /var/lib/apt/lists/*

ENV WORKPATH /go/src/github.com/openark/orchestrator
WORKDIR $WORKPATH

RUN curl -O "https://raw.githubusercontent.com/openark/orchestrator-ci-env/master/bin/linux/dbdeployer.gz"
RUN curl -O "https://raw.githubusercontent.com/openark/orchestrator-ci-env/master/mysql-tarballs/mysql-5.7.26.tar.xz"
RUN gunzip ./dbdeployer.gz
RUN chmod +x ./dbdeployer
RUN mkdir -p ./sandbox/binary

RUN ./dbdeployer unpack mysql-5.7.26.tar.xz --sandbox-binary $WORKPATH/sandbox/binary

COPY . .

CMD ["script/test-all"]
