#!/bin/bash

set -e

. script/bootstrap

echo "Verifying code is formatted via 'gofmt -s -w  go/'"
gofmt -s -w  go/
git diff --exit-code --quiet

echo "Building"
script/build

cd .gopath/src/github.com/outbrain/orchestrator

echo "Running unit tests"
go test ./go/...

echo "Running integration tests"
./tests/integration/test.sh

mysql test -e "show grants for current_user()"

echo "Done"
