#!/bin/bash

set -e

. script/bootstrap

echo "Verifying code is formatted via 'gofmt -s -w  go/'"
gofmt -s -w  go/
git diff --exit-code --quiet

echo "Building"
script/build

cd .gopath/src/github.com/outbrain/orchestrator

echo "Running unit tests"
go test ./go/...

echo "checking mysql 1"
mysql -e "select @@hostname"
echo "checking mysql 2"
mysql -e "show grants for current_user"
echo "checking mysql 3"
mysql -e "show databases"
echo "checking mysql 4"
mysql -e "no such query"
