#!/bin/bash

echo "directory1 is $(pwd)"
echo "GOPATH is ${GOPATH}"
ls -l .gopath
cd .gopath/src/github.com/github/orchestrator
echo "directory2 is $(pwd)"

unit_tests() {
  echo "# Running unit tests"
  go test ./go/...
}

unit_tests
