#!/bin/bash

validate_source_code_conventions() {
  echo "# Verifying code is formatted via 'gofmt -s -w  go/'"
  gofmt -s -w  go/
  git diff --exit-code --quiet go/
}

validate_source_code_conventions
