#!/bin/bash

echo "# topology:"
orchestrator-client -c topology-tabulated -alias ci
echo "# replication-analysis:"
orchestrator-client -c replication-analysis
echo "# haproxy"
cat /etc/haproxy/haproxy.cfg
