#!/bin/bash

if [ ! -f orchestrator-ci-env/script/deploy-replication ] ; then
  echo "ERROR: teardown_redeploy indicated, but orchestrator-ci-env not found"
  exit 1
fi

(cd orchestrator-ci-env && script/deploy-replication > $deploy_replication_file 2>&1)
# orchestrator's cached connections will have been invalid now. Force refresh by
# probing all instances:
orchestrator-client -c discover -i 127.0.0.1:10111 > /dev/null 2>&1
orchestrator-client -c discover -i 127.0.0.1:10112 > /dev/null 2>&1
orchestrator-client -c discover -i 127.0.0.1:10113 > /dev/null 2>&1
orchestrator-client -c discover -i 127.0.0.1:10114 > /dev/null 2>&1
sleep 10
