#!/bin/bash

orchestrator-client -c end-downtime -i 127.0.0.1:10111
orchestrator-client -c end-downtime -i 127.0.0.1:10112
orchestrator-client -c end-downtime -i 127.0.0.1:10113
orchestrator-client -c end-downtime -i 127.0.0.1:10114
